### ISSUE TITLE
Dépendance manquante CanonicalUrl

### ISSUE THREAD

**Issue by gillesbourgeat** [thelia-modules/BetterSeo#4]
https://github.com/thelia-modules/BetterSeo/blob/020e5336dfcc28e82cb1840441760cfeb95b58ce/composer.json#L6

Il manque l'indication comme quoi il faut le module CanonicalUrl (idem dans module.xml)

**Comment by lopes-vincent** [comment]
Corrigé, le module CanonicalUrl n'est plus obligatoire 😉
https://github.com/thelia-modules/BetterSeo/blob/master/EventListeners/SeoListener.php#L79
